# Generated by Django 4.2.3 on 2023-07-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_message_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-added_at',)},
        ),
    ]
